// Precompute the county map mesh.
//
//   node scripts/build-mesh.mjs
//
// WHY
//
// Opening the map ran buildMesh() in the browser: decode every TopoJSON arc,
// project 3,199 counties, normalise, simplify, and measure bounding boxes.
// Measured on a desktop, first map open cost 5.0s — 1.06s to fetch and parse
// county-shapes.json, then 3.9s of buildMesh with the main thread pinned. A
// phone is several times worse. Nothing else can run during it: no scroll, no
// tap, no tab switch. On an older device that is a frozen app, which is the
// same 2.1 territory this project has already been rejected in once.
//
// None of that work depends on anything the browser knows. It is the same
// answer every time, for every reader. So it moves here.
//
// OUTPUT, two files:
//   data/county-mesh.bin   every ring's coordinates, one Float32Array, packed
//                          back to back. The browser maps subarray views over
//                          it — no copying, no per-ring allocation.
//   data/county-mesh.json  the index: width, height, mainlandCenter, and per
//                          county its fips, centroid, size, bbox and the
//                          [offset, length] of each of its rings in the blob.
//
// Both are national and byte-identical for every reader, so they carry the
// same privacy shape as every other bundle — no per-county request.
//
// The browser keeps buildMesh() as a fallback. If these files are missing or
// stale the map still works, just slowly, which is the right failure mode for
// a build artifact.

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildMesh } from "../site/js/mesh.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const p = (...a) => path.join(ROOT, ...a);

const readJson = async (f) => JSON.parse(await readFile(f, "utf8"));

const t0 = Date.now();
const shapes = await readJson(p("data/county-shapes.json"));
const gaz = await readJson(p("data/counties.json"));

const mesh = buildMesh(shapes, gaz.counties);
const built = Date.now() - t0;

/* Pack every ring into one Float32Array, in county order.
 *
 * The index carries ONLY what cannot be recovered from the blob: the fips and
 * the length of each ring. Offsets accumulate on load, and the centroid, size
 * and bounding box are one cheap pass over 22k points in the browser - about a
 * millisecond, against the 341 KB of JSON it would take to ship them. That is
 * the difference between a 341 KB index and a 60 KB one. */
let total = 0;
for (const c of mesh.counties) for (const r of c.rings) total += r.length;

const blob = new Float32Array(total);
let at = 0;
const counties = mesh.counties.map((c) => {
  const lens = [];
  for (const r of c.rings) {
    blob.set(r, at);
    at += r.length;
    lens.push(r.length);
  }
  return [c.fips, ...lens];
});

const index = {
  note: "Generated by scripts/build-mesh.mjs. Do not hand-edit. Rings live in county-mesh.bin, packed in this order; each entry is [fips, ...ringLengths]. Offsets, centroid, size and bbox are derived on load.",
  generated: new Date().toISOString(),
  width: mesh.width,
  height: mesh.height,
  mainlandCenter: mesh.mainlandCenter,
  floats: total,
  counties,
};

await writeFile(p("data/county-mesh.bin"), Buffer.from(blob.buffer, 0, blob.byteLength));
await writeFile(p("data/county-mesh.json"), JSON.stringify(index) + "\n");

const kb = (b) => `${(b / 1024).toFixed(0)} KB`;
console.log(`county mesh precomputed in ${built} ms`);
console.log(`  counties   ${counties.length}`);
console.log(`  rings      ${counties.reduce((n, c) => n + c.length - 1, 0)}`);
console.log(`  bin        ${kb(blob.byteLength)}`);
console.log(`  index      ${kb(Buffer.byteLength(JSON.stringify(index)))}`);
